name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reproduce:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          set -eux
          if [ -f env/requirements.txt ]; then
            pip install --prefer-binary -r env/requirements.txt
          else
            printf "numpy\nscipy\nmatplotlib\npandas\n" > requirements-ci.txt
            pip install --prefer-binary -r requirements-ci.txt
          fi
          pip install --only-binary=:all: numpy scipy || true

      - name: Sanity check files
        run: |
          ls -l src/repro_batch.py
          ls -l data-min/interesting_stream.npy data-min/custom_D.npy

      - name: Compile check (fast fail)
        run: python -m py_compile src/repro_batch.py

      - name: Run headless repro
        run: |
          set -euxo pipefail
          mkdir -p outputs
          python -V | tee outputs/env_versions.txt
          python -c "import numpy as n, scipy as s; print('NumPy', n.__version__); print('SciPy', s.__version__)" | tee -a outputs/env_versions.txt
          python src/repro_batch.py \
            --x data-min/interesting_stream.npy \
            --dict custom --D data-min/custom_D.npy \
            --m 1400 --lam 0.02 --nu phase --seed 12345 \
            --out outputs |& tee outputs/repro_log.txt
          pip freeze > outputs/pip_freeze.txt

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: srtt-repro-artifacts
          path: outputs/**
          if-no-files-found: warn
