name: reproduce
on: [push, pull_request]
jobs:
  run-repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Upgrade build tooling
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install deps (with retry)
        run: |
          for i in 1 2 3; do
            pip install -r env/requirements.txt && break || sleep 10
          done
      - name: Run headless repro
        run: |
          mkdir -p outputs
          python src/repro_batch.py \
            --x data-min/interesting_stream.npy \
            --dict custom --D data-min/custom_D.npy \
            --m 1400 --lam 0.02 --nu phase --seed 12345 \
            --out outputs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: srtt-repro-artifacts
          path: outputs/**
