name: reproduce-manual
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MPLBACKEND: Agg
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps (simple)
        run: pip install --prefer-binary numpy scipy matplotlib pandas
      - name: Sanity: files present
        run: ls -l src/repro_batch.py data-min/interesting_stream.npy data-min/custom_D.npy
      - name: Run headless repro
        run: |
          mkdir -p outputs
          python src/repro_batch.py \
            --x data-min/interesting_stream.npy \
            --dict custom --D data-min/custom_D.npy \
            --m 1400 --lam 0.02 --nu phase --seed 12345 \
            --out outputs
      - name: List outputs (debug)
        if: always()
        run: ls -la outputs || true
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: srtt-repro-artifacts
          path: outputs/**
